CREATE TABLE `partner_onboarding_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(255) NOT NULL,
	`currentStep` int NOT NULL DEFAULT 1,
	`completedSteps` json NOT NULL DEFAULT ('[]'),
	`companyName` varchar(255),
	`website` varchar(255),
	`phone` varchar(50),
	`address` text,
	`city` varchar(100),
	`state` varchar(50),
	`country` varchar(100),
	`zipCode` varchar(20),
	`partnerType` enum('Reseller','Technology Partner','System Integrator','Managed Service Provider','Consulting Partner','Channel Partner','OEM Partner','Other'),
	`tier` enum('Gold','Silver','Bronze','Standard'),
	`mdfBudgetAnnual` decimal(12,2),
	`primaryContactName` varchar(255),
	`primaryContactEmail` varchar(320),
	`primaryContactPhone` varchar(50),
	`status` enum('In Progress','Completed','Abandoned') NOT NULL DEFAULT 'In Progress',
	`completedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_onboarding_sessions_id` PRIMARY KEY(`id`)
);
