CREATE TABLE `partner_companies` (
  `id` int AUTO_INCREMENT NOT NULL,
  `companyName` varchar(255) NOT NULL,
  `website` varchar(255),
  `phone` varchar(50),
  `email` varchar(320) NOT NULL,
  `address` text,
  `city` varchar(100),
  `state` varchar(50),
  `country` varchar(100),
  `zipCode` varchar(20),
  `partnerType` enum('Reseller','Technology Partner','System Integrator','Managed Service Provider','Consulting Partner','Channel Partner','OEM Partner','Other') NOT NULL,
  `partnerStatus` enum('Prospect','Active','Inactive','Suspended','Terminated') NOT NULL DEFAULT 'Prospect',
  `tier` enum('Gold','Silver','Bronze','Standard') DEFAULT 'Standard',
  `primaryContactName` varchar(255) NOT NULL,
  `primaryContactEmail` varchar(320) NOT NULL,
  `primaryContactPhone` varchar(50),
  `commissionRate` decimal(5,2) DEFAULT '10.00',
  `mdfBudgetAnnual` decimal(15,2) DEFAULT '0.00',
  `description` text,
  `logoUrl` varchar(512),
  `certifications` text,
  `specializations` text,
  `accountManagerId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partner_companies_id` PRIMARY KEY(`id`),
  KEY `status_idx` (`partnerStatus`),
  KEY `type_idx` (`partnerType`),
  KEY `manager_idx` (`accountManagerId`)
);

CREATE TABLE `partner_users` (
  `id` int AUTO_INCREMENT NOT NULL,
  `userId` int,
  `partnerCompanyId` int NOT NULL,
  `email` varchar(320) UNIQUE,
  `passwordHash` varchar(255),
  `emailVerified` boolean DEFAULT false,
  `contactName` varchar(255),
  `phone` varchar(50),
  `partnerRole` enum('Admin','Account Manager','Sales Rep','Technical','Finance','Support','Other') NOT NULL DEFAULT 'Sales Rep',
  `isActive` boolean DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partner_users_id` PRIMARY KEY(`id`),
  KEY `partner_idx` (`partnerCompanyId`),
  KEY `user_idx` (`userId`),
  KEY `email_idx` (`email`)
);

CREATE TABLE `partner_deals` (
  `id` int AUTO_INCREMENT NOT NULL,
  `dealName` varchar(255) NOT NULL,
  `partnerCompanyId` int NOT NULL,
  `customerName` varchar(255),
  `customerEmail` varchar(320),
  `dealAmount` varchar(50),
  `dealStage` enum('Prospecting','Qualification','Proposal','Negotiation','Closed Won','Closed Lost') DEFAULT 'Prospecting',
  `expectedCloseDate` date,
  `description` text,
  `productInterest` text,
  `submittedBy` int,
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partner_deals_id` PRIMARY KEY(`id`),
  KEY `company_idx` (`partnerCompanyId`),
  KEY `stage_idx` (`dealStage`)
);

CREATE TABLE `partnerMdfClaims` (
  `id` int AUTO_INCREMENT NOT NULL,
  `partnerCompanyId` int NOT NULL,
  `claimName` varchar(255) NOT NULL,
  `description` text,
  `campaignType` enum('Co-Marketing','Sales Enablement','Training','Events','Digital Marketing','Other') DEFAULT 'Sales Enablement',
  `requestedAmount` varchar(50),
  `status` enum('Submitted','Approved','Rejected','Paid') DEFAULT 'Submitted',
  `submittedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submittedBy` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `partnerMdfClaims_id` PRIMARY KEY(`id`),
  KEY `company_idx` (`partnerCompanyId`),
  KEY `status_idx` (`status`)
);
